$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
name: mm-endpoint-072021a
type: online
auth_mode: key
traffic:
  blue: 100

deployments:
  #blue deployment
  - name: blue
    model:
      name: model-1
      version: 1
      local_path: nyc_model.pkl
    code_configuration:
      code: 
        local_path: .
      scoring_script: score.py
    environment: 
      name: env-model1
      version: 1
      path: .
      conda_file: file:condadep.yml
      docker:
          image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:20210301.v1
    instance_type: Standard_F2s_v2
    scale_settings:
      scale_type: manual
      instance_count: 1
      min_instances: 1
      max_instances: 2